version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENABLE_MQTT_BRIDGE=${ENABLE_MQTT_BRIDGE:-true}
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-mosquitto}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
      - MQTT_BASE_TOPIC=${MQTT_BASE_TOPIC:-motospect/v1}
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host ${BACKEND_HOST:-0.0.0.0} --port ${BACKEND_PORT:-8000} --reload
    depends_on:
      - mosquitto

  frontend:
    build: ./frontend
    container_name: motospect-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_USE_MQTT=false
      - REACT_APP_BACKEND_URL=http://localhost:8084
      - REACT_APP_MQTT_URL=ws://localhost:9001
      - REACT_APP_MQTT_BASE_TOPIC=motospect/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  customer-portal:
    build: ./customer-portal
    container_name: motospect-customer-portal
    ports:
      - "3040:3040"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8084
      - REACT_APP_REPORT_URL=http://localhost:3050
    volumes:
      - ./customer-portal:/app
      - /app/node_modules
    command: npm start

  report-service:
    build: ./report-service
    container_name: motospect-report-service
    ports:
      - "3050:3050"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8084
    volumes:
      - ./report-service:/app
      - /app/node_modules
    command: npm start

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"    # MQTT TCP
      - "9001:9001"    # MQTT over WebSocket
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  firmware:
    build:
      context: ./firmware
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_BASE_TOPIC=motospect/v1
    depends_on:
      - mosquitto
