---
# Ansible inventory for MOTOSPECT

all:
  children:
    development:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          
    staging:
      hosts:
        staging-server:
          ansible_host: staging.motospect.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/motospect_staging.pem
          
    production:
      hosts:
        prod-server-1:
          ansible_host: prod1.motospect.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/motospect_prod.pem
        prod-server-2:
          ansible_host: prod2.motospect.com
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/motospect_prod.pem
          
  vars:
    project_name: motospect
    docker_registry: motospect
    backend_port: 8030
    frontend_port: 3030
    customer_portal_port: 3040
